### PR TITLE
Update notes.txt

### PR DESCRIPTION
**Pull request by bmorris3**
Here's a change I'm proposing.

### CODE REVIEW

**Comment by jakevdp** [comment]
Hey I like this – thanks for contributing!

**Comment by bmorris3** [comment]
Are you sure? I'm crazy :metal:

**Comment by jakevdp** [comment]
:smile_cat:

**Comment by bmorris3** [comment]
Knowing Python is the best :rainbow:

**Comment by bmorris3** [comment]
Thanks again!

**Pull request merged**
